Results page
hack4impact-uiuc/childs-play-tool pull request #29
Opened 2018-10-14 03:16 UTC by Feeshay

f

2018-10-16 03:22 UTC, hanarimawi requested changes
Make toggle function arrow function instead of bind

2018-10-16 03:29 UTC, hanarimawi approved these changes

2018-10-16 03:34 UTC, angadgarg25 commented on frontend/src/components/Results.js
> +  toggle(tab) {
If you change this to `toggle = tab => {...}` you don't need to do the bind in the constructor, which makes the code cleaner.

2018-10-16 04:34 UTC, caiyingshen approved these changes
looks good!!

2018-10-17 01:27 UTC, angadgarg25 approved these changes
Looks good! :)

2018-10-17 01:46 UTC, merged