WORK
hack4impact-uiuc/childs-play-tool pull request #39
Opened 2018-10-24 23:40 UTC by Feeshay

2018-11-01 00:31 UTC, angadgarg25 requested changes
See comments, should be pretty quick.
Also theres a couple `.DS_Store`s that need to be removed.

2018-11-01 00:31 UTC, angadgarg25 commented on frontend/src/components/Tag.js
> +  }
We have constants for these, lets use them

2018-11-01 00:31 UTC, angadgarg25 commented on frontend/src/components/SearchPage.js
> +            Hello! Welcome to the Child's Play Game Finder. You can search a game by name or filter
Use `&#39;` instead of `'` so that it renders nicely on github

2018-11-01 00:31 UTC, angadgarg25 commented on frontend/src/components/Results.js
> +    else return
Lets use the constants file here too, and maybe switch case instead.

2018-11-02 01:57 UTC, angadgarg25 approved these changes

2018-11-03 21:59 UTC, hanarimawi approved these changes

2018-11-03 22:38 UTC, merged